### ISSUE TITLE
[BUG] - Paramètre manquant sur la partie Accueil 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/theme-rainfall#1]
# 🐞️ Bug report

## Environment
- CMW Version: Alpha-02

## Bug Description
Il n'est pas possible de modifier le texte "Une super description ..." 

## Observed Behavior
Ajouter le paramètre manquant sur le panel admin 

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/b8894c39-591b-4985-9548-5d7c681366c9)
Le texte dont je parle 

![image](https://github.com/user-attachments/assets/f71d9d5b-eba8-4973-986a-444c90da4026)
Le paramètre inexistant

**Comment by Zomblard** [comment]
Fixed : https://github.com/CraftMyWebsite/theme-rainfall/commit/9cecb744798b9664b424bd8c7bab420b8ccbd6eb
